/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from "react";
import { useGLTF } from "@react-three/drei";

interface Props {
  color: string;
}

export function Model(props: Props) {
  const gltf = useGLTF("/crash_bandicoot.gltf") as any;

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.default_1.geometry}
          material={gltf.materials["None.003"]}
        >
          <Material color={props.color} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.default_2.geometry}
          material={gltf.materials["None.002"]}
        >
          <Material color={props.color} />
        </mesh>
      </group>
    </group>
  );
}

function Material(props: { color: string }) {
  return (
    <meshStandardMaterial
      attach="material"
      emissive={props.color}
      emissiveIntensity={30.}
      color={props.color}
      wireframe
      toneMapped={false}
    />
  )
}

useGLTF.preload("/crash_bandicoot.gltf");
